import { appColors } from "@/shared/config";

const colors = {
  separator: appColors.separator,
  surfaceRaised: appColors.surfaceRaised,
  textPrimary: appColors.textPrimary,
  textSecondary: appColors.textSecondary,
  textTertiary: appColors.textTertiary,
  searchBackground: appColors.searchBackground,
} as const;

export const styles = {
  searchSection: {
    marginTop: 18,
  },
  searchField: {
    width: "100%",
    boxSizing: "border-box" as const,
    background: colors.searchBackground,
    borderRadius: 16,
    boxShadow: `inset 0 0 0 1px ${colors.separator}`,
  },
  searchFieldIcon: {
    width: 18,
    height: 18,
    display: "block",
    color: colors.textSecondary,
  },
  tableWrapper: {
    borderRadius: 22,
    overflow: "clip",
    border: `1px solid ${colors.separator}`,
    marginTop: 12,
  },
  tableRoot: {
    width: "100%",
    borderCollapse: "collapse" as const,
    background: colors.surfaceRaised,
    tableLayout: "fixed" as const,
  },
  tableHeader: {
    background: colors.surfaceRaised,
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
  },
  tableHeaderCell: {
    padding: "12px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textTertiary,
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.separator}`,
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  tableHeaderCellUuid: {
    padding: "12px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textTertiary,
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.separator}`,
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  tableHeaderCellCheckbox: {
    padding: "13px 16px",
    borderBottom: `1px solid ${colors.separator}`,
    verticalAlign: "middle" as const,
    width: 48,
    boxSizing: "border-box" as const,
  },
  tableRow: {
    borderBottom: `1px solid ${colors.separator}`,
  },
  tableRowLast: {},
  tableCellId: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 400,
    color: colors.textSecondary,
    verticalAlign: "middle" as const,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis",
  },
  tableCellName: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: colors.textPrimary,
    verticalAlign: "middle" as const,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis",
  },
  tableCellCheckbox: {
    padding: "13px 16px",
    verticalAlign: "middle" as const,
    width: 48,
    boxSizing: "border-box" as const,
  },
  tableHeaderCellSource: {
    padding: "12px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textTertiary,
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.separator}`,
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  tableCellSource: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 400,
    color: colors.textSecondary,
    verticalAlign: "middle" as const,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis",
  },
  errorText: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.5,
    color: colors.textSecondary,
    textAlign: "center" as const,
    padding: "28px 24px",
  },
  emptyText: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.5,
    color: colors.textSecondary,
    textAlign: "center" as const,
    padding: "28px 24px",
  },
  skeletonRow: {
    borderBottom: `1px solid ${colors.separator}`,
  },
  skeletonCell: {
    padding: "13px 16px",
    verticalAlign: "middle" as const,
  },
  skeletonLine: {
    background: "rgba(118, 118, 128, 0.16)",
    borderRadius: 999,
    height: 14,
    width: "60%",
  },
  headerCheckboxInput: {
    display: "block" as const,
    width: 16,
    height: 16,
    margin: 0,
    cursor: "pointer",
    accentColor: colors.textPrimary,
    flexShrink: 0,
  },
} as const;
