import { appColors } from "@/shared/ui";

const colors = {
  separator: appColors.separator,
  surfaceRaised: appColors.surfaceRaised,
  errorBackground: appColors.errorBackground,
  errorBorder: appColors.errorBorder,
  error: appColors.error,
  textPrimary: appColors.textPrimary,
  textSecondary: appColors.textSecondary,
  textSubtle: appColors.textSubtle,
  textTertiary: appColors.textTertiary,
  searchBackground: appColors.searchBackground,
} as const;

export const styles = {
  heroSection: {
    paddingBottom: 6,
  },
  pageTitle: {
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: -0.7,
    color: colors.textPrimary,
    margin: "6px 0 0 0",
    lineHeight: 1.02,
  },
  pageSubtitle: {
    fontSize: 15,
    color: colors.textSecondary,
    margin: "8px 0 0 0",
  },
  searchSection: {
    marginTop: 18,
  },
  searchField: {
    width: "100%",
    boxSizing: "border-box" as const,
    background: colors.searchBackground,
    borderRadius: 16,
    boxShadow: `inset 0 0 0 1px ${colors.separator}`,
  },
  searchFieldIcon: {
    width: 18,
    height: 18,
    display: "block",
    color: colors.textSecondary,
  },
  listSection: {
    marginTop: 26,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap" as const,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 600,
    color: colors.textPrimary,
    letterSpacing: -0.2,
  },
  tableRoot: {
    width: "100%",
    borderCollapse: "collapse" as const,
    background: colors.surfaceRaised,
    border: `1px solid ${colors.separator}`,
    borderRadius: 22,
    overflow: "hidden",
    boxShadow: "0 18px 42px rgba(15, 23, 42, 0.06)",
  },
  tableHeader: {
    background: colors.surfaceRaised,
  },
  tableHeaderCell: {
    padding: "12px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textTertiary,
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.separator}`,
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  tableHeaderCellId: {
    padding: "12px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textTertiary,
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.separator}`,
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
    width: 60,
  },
  tableRow: {
    borderBottom: `1px solid ${colors.separator}`,
  },
  tableRowLast: {},
  tableCellId: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: colors.textSecondary,
    verticalAlign: "middle" as const,
    width: 60,
  },
  tableCellName: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: colors.textPrimary,
    verticalAlign: "middle" as const,
  },
  tableCellDescription: {
    padding: "13px 16px",
    fontSize: 14,
    color: colors.textSubtle,
    verticalAlign: "middle" as const,
  },
  tableCellCount: {
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: colors.textPrimary,
    verticalAlign: "middle" as const,
    width: 100,
  },
  skeletonRow: {
    borderBottom: `1px solid ${colors.separator}`,
  },
  skeletonCell: {
    padding: "13px 16px",
    verticalAlign: "middle" as const,
  },
  skeletonLine: {
    background: "rgba(118, 118, 128, 0.16)",
    borderRadius: 999,
    height: 14,
  },
  emptyText: {
    margin: "28px 24px",
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: "center" as const,
  },
  errorCard: {
    marginTop: 24,
    padding: "18px 20px",
    borderRadius: 18,
    background: colors.errorBackground,
    border: `1px solid ${colors.errorBorder}`,
    color: colors.error,
  },
  inlineErrorCard: {
    marginTop: 16,
    borderRadius: 18,
    background: colors.errorBackground,
    border: `1px solid ${colors.errorBorder}`,
  },
  errorTitle: {
    fontSize: 15,
    fontWeight: 700,
    margin: 0,
  },
  errorText: {
    fontSize: 14,
    lineHeight: 1.45,
    margin: "6px 0 0 0",
  },
} as const;
